# Generated by Django 3.1.7 on 2021-04-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='main_question',
            new_name='is_main_question',
        ),
    ]
