# Generated by Django 3.1.7 on 2021-04-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='main_question',
            field=models.BooleanField(default=False),
        ),
    ]
