# Generated by Django 3.1.7 on 2021-04-08 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_auto_20210409_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
