# Generated by Django 3.1.7 on 2021-04-08 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0004_auto_20210409_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
